============================= test session starts ==============================
platform linux -- Python 3.11.3, pytest-7.4.0, pluggy-1.2.0
rootdir: /home/pedro/dev/py/toguishi
collected 4 items

src/db/test_db.py ..FF                                                   [100%]

=================================== FAILURES ===================================
____________________________ test_get_store_by_name ____________________________

db_manager = <db.db_manager.DBManager object at 0x7fa776a3a350>

    def test_get_store_by_name(db_manager):
        store = Store(
            "Focinho Feliz", "Asa Norte SQN 216 BL A", [Phone("(61)986792020")], db_manager
        )
        store.save()
        retrieved_store = db_manager.get_store_by_name("Focinho Feliz")
        assert retrieved_store is not None
>       assert retrieved_store["name"] == "Focinho Feliz"
E       TypeError: tuple indices must be integers or slices, not str

src/db/test_db.py:38: TypeError
__________________________ test_get_customer_by_name ___________________________

db_manager = <db.db_manager.DBManager object at 0x7fa7769fed10>

    def test_get_customer_by_name(db_manager):
        store = Store(
            "Focinho Feliz", "Asa Norte SQN 216 BL A", [Phone("(61)986792020")], db_manager
        )
>       store.save()

src/db/test_db.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/customer/store.py:27: in save
    store_id = self.db_manager.insert_store(self)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <db.db_manager.DBManager object at 0x7fa7769fed10>
store = Customer('Focinho Feliz', 'Asa Norte SQN 216 BL A' ,[Phone('(61)986792020')], <db.db_manager.DBManager object at 0x7fa7769fed10>)

    def insert_store(self, store):
        self.cursor.execute(
            "INSERT INTO stores (name, address) VALUES (?, ?)",
            (store.name, store.address),
        )
        store_id = self.cursor.lastrowid
>       self.connection.commit()
E       sqlite3.OperationalError: database is locked

src/db/db_manager.py:46: OperationalError
=========================== short test summary info ============================
FAILED src/db/test_db.py::test_get_store_by_name - TypeError: tuple indices m...
FAILED src/db/test_db.py::test_get_customer_by_name - sqlite3.OperationalErro...
========================= 2 failed, 2 passed in 5.09s ==========================
